baseurl      = "http://vonernue.me/"
title        = "Vonernue"
languageCode = "en"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "CSIE Undergrad at NTNU"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "CSIE Undergrad at NTNU"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Vonernue"
    subtitle = "CSIE Undergrad at NTNU"
    keywords = ""
    copyright = "Vonernue"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "VONERNUE"
      logoHomeLink = "/"
    # or
    #
      path = "/img/vonernue_icon.png"
      alt = "Vonernue"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = -10
  [[menu.main]]
    identifier = "github"
    name       = "Github"
    url        = "https://github.com/seanho12345/"
    weight     = 0