baseurl      = "http://vonernue.me/"
title        = "Vonernue"
languageCode = "en"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "CSIE Undergrad at NTNU"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "CSIE Undergrad at NTNU"
  keywords = "homepage, blog"
  images = [""]

  #Portait on homepage
  [params.portrait]
    path     = "/img/vonernue_icon.png"
    alt      = "Portrait"
    maxWidth = "50px"

  #Set Social Icon on homepage
  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/seanho12345/"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/vonernue/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/seanho12345"

  [[params.social]]
    name = "email"
    url  = "mailto:seano12345@gmail.com"


  [params.logo]
    logoMark     = ">"
    logoText     = "Vonernue"
    logoHomeLink = "/"
    logoCursorColor = "#6FF7F0"
    # path = "/img/vonernue_icon.png"
    # alt = "Vonernue"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Vonernue"
    subtitle = "CSIE Undergrad at NTNU"
    keywords = ""
    copyright = "Vonernue"
    readOtherPosts = "Read other posts"

    #[languages.en.params.logo]
    #  logoText = "VONERNUE"
    # logoHomeLink = "/"
    # or
    #
    # path = "/img/vonernue_icon.png"
    # alt = "Vonernue"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = -100
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = -10
  [[menu.main]]
    identifier = "playlist"
    name       = "Playlist"
    url        = "/playlist"
    weight     = -5
  [[menu.main]]
    identifier = "github"
    name       = "Github"
    url        = "https://github.com/seanho12345/"
    weight     = 0

